### ISSUE TITLE
Add AlfanousDesktop to Debian project software repository

### ISSUE THREAD

**Issue by assem-ch** [Alfanous-team/alfanous#111]
http://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html

**Comment by sneetsher** [comment]
@assem-ch , could you:

- remove me_quran because it is not DFSG-compatible (may be create a separate repo for non-free components)
- add licenses for other fonts: [Scheherazade](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=Scheherazade) OFLv1.1, [arabeyes-quran](https://gitlab.com/arabeyes-art/khotot) GPLv2

**Comment by sneetsher** [comment]
- Submitted an ITP notice: [debian-bug#861621](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861622&archived=False&mbox=no)
- Request for membership to: [Python Applications Packaging Team (PAPT)](https://wiki.debian.org/Teams/PythonAppsPackagingTeam) at https://alioth.debian.org/

Hope for some response, I see too many requests.

**Comment by sneetsher** [comment]
@assem-ch could you create an account in https://alioth.debian.org/ . We may need to create a source code mirror there soon or later. Ref: https://wiki.debian.org/Alioth/PackagingProject
